matrix:
  include:
    - language: go
      go:
        - "1.10.x"
      script:
        - go build
      go_import_path: github.com/PSUSWENG894/BudgetAPI

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: sf-budget-api
  on:
    branch: master
