matrix:
  include:
    - language: go
      go:
        - "1.10.x"
      script:
        - go build

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app:
    sf-budget-api
  on:
    branch: master
